# Generated by Django 5.1.7 on 2025-04-30 21:22

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_period', models.CharField(choices=[('Ilamian', 'ایلامیان'), ('Achaemenid', 'هخامنشیان'), ('Ilkhanid', 'ایلخانیان'), ('Parthian', 'اشکانیان'), ('Timurid', 'تیموریان'), ('Sassanid', 'ساسانیان'), ('Safavid', 'صفویان'), ('Seljuk', 'سلجوقیان'), ('Qajar', 'قاجار'), ('Uncertain', 'نامشخص')], default='Uncertain', max_length=20)),
                ('attraction_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('opening_hours', models.CharField(blank=True, max_length=100)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='attractions/')),
                ('built_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تاریخ بازگشت')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='ساعت حرکت')),
                ('return_time', models.TimeField(blank=True, null=True, verbose_name='ساعت برگشت')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField()),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('accommodation', models.TextField(blank=True, null=True)),
                ('meal_details', models.TextField(blank=True, null=True)),
                ('transportation', models.TextField(blank=True, null=True)),
                ('travel_insurance', models.TextField(blank=True, null=True)),
                ('tourism_services', models.TextField(blank=True, null=True)),
                ('tour_guides_info', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('attractions', models.ManyToManyField(related_name='tours', to='tour.attraction')),
                ('related_tours', models.ManyToManyField(blank=True, related_name='similar_tours', to='tour.tour')),
                ('tour_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tours', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(help_text='مثلاً روز اول', max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='daily_schedules/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_passengers', models.PositiveIntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tour.tour')),
            ],
        ),
    ]
