# Generated by Django 5.1.7 on 2025-04-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='headers/')),
                ('alt_text', models.CharField(max_length=255)),
                ('show_on_homepage', models.BooleanField(default=False)),
            ],
        ),
    ]
